Feature/individual readouts
calculquebec/pennylane-snowflurry pull request #4
Opened 2024-03-28 18:55 UTC by Scirelgar

## Description

Added handling for multiple measurement processes returned by a single QNode.

## Related Issues

Resolves calculquebec/MonarQ-Hub#10

2024-03-28 19:00 UTC, Scirelgar commented
https://github.com/calculquebec/MonarQ-Hub/issues/10

2024-04-02 17:17 UTC, AntoineLemelin requested changes
Overall ça me semble bien juste regarder les commentaires. Good job !

2024-04-02 17:17 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +                if "Gate Object" in gate_str:
Peut-être mettre une variable global, car si ça change sa peut-être dur a retrouver. Sinon est ce que pennylane a déjà un objet défini pour ça?

2024-04-02 17:17 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +                        r"Gate Object: (.*)\nConnected_qubits", gate_str
Surtout qu'on retrouve le string a plusieurs reprise

2024-04-02 17:17 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +                    gate_name = "Readout"
Même chose pour le string readout

2024-04-02 17:17 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +            self.remove_readouts()
Juste être sur est ce que tu les removes pour les reapply ?

2024-04-03 14:25 UTC, Scirelgar reviewed
J'ai laissé une question et une explication. Je vais fix le edge case qui n'avait pas été adressé

2024-04-03 14:25 UTC, Scirelgar commented on pennylane_snowflurry/pennylane_converter.py
> +                if "Gate Object" in gate_str:
Genre un attribut de classe pour stocker le dictionnaire ou pour une variable dans la fonction pour `gate_string` et `gate_name`?
```py
ops = []
instructions = Main.sf_circuit.instructions
gate_str = ''
gate_name= ''
```

2024-04-03 14:25 UTC, Scirelgar commented on pennylane_snowflurry/pennylane_converter.py
> +            self.remove_readouts()
Les measurement processes qui demandent pas de readout, aka. ceux qui utilisent Main.simulate(), retirent tous les Readouts gates du circuit.

Admettons que je finis un circuit comme suit en PennyLane, le pull request devrait faire ce qui est en commentaire
```py
return (
        qml.sample(qml.PauliZ(0)), # Ajoute un readout fil 1 vers bit 1
        qml.state(), # Enleve tout
        qml.sample(qml.PauliZ(1)),  # Ajoute un readout fil 2 vers bit 2
    )
```
Par contre je viens de voir que je n'ai pas pris en compte le cas suivant:
```py
return (
        qml.sample(qml.PauliZ(0)), # Ajoute un readout fil 1 vers bit 1
        qml.sample(), # Ajoute un readout sur tout et cause une erreur Snowflurry
    )
```

2024-04-03 14:35 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +                if "Gate Object" in gate_str:
Je suis un peu hésitant mais j'irais pour une variable de classe, car c'est plus simple a aller changer et a trouver!

2024-04-03 14:37 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +            self.remove_readouts()
Ok parfait je laisse alors le fix ouvert pour que tu gardes la trace pour aller corriger ce cas d'usage. C'est aussi un test que tu devras ajouter a tes tests unitaires. Comme toutes les autres fonctions de mesure.

2024-04-03 20:13 UTC, AntoineLemelin commented on pennylane_snowflurry/pennylane_converter.py
> +                if self.snowflurry_GateObject_name in gate_str:
C'est vraiment un détail, mais normalement on évite le camel case avec le snail_caise

2024-04-03 20:19 UTC, merged